openapi: 3.0.0
info:
  title: Authentication API for Docusaurus Website
  description: API for handling user authentication, profile management, and personalization settings
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging-api.example.com/v1
    description: Staging server

paths:
  /auth/login:
    post:
      summary: Login a user
      description: Authenticate user with email/password or OAuth credentials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  format: password
                  description: User's password (optional for OAuth)
                provider:
                  type: string
                  enum: [email, google, github]
                  description: Authentication provider
                oauthToken:
                  type: string
                  description: OAuth token (for OAuth flows)
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  session:
                    $ref: '#/components/schemas/Session'
                  token:
                    type: string
                    description: Authentication token
        '401':
          description: Invalid credentials
        '400':
          description: Invalid request format

  /auth/signup:
    post:
      summary: Register a new user
      description: Create a new user account with background information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/User'
                - type: object
                  properties:
                    password:
                      type: string
                      format: password
                      description: User's password
                    backgroundInfo:
                      $ref: '#/components/schemas/BackgroundInfo'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  session:
                    $ref: '#/components/schemas/Session'
        '409':
          description: Email already exists
        '400':
          description: Invalid request format


  /auth/me:
    get:
      summary: Get current user
      description: Retrieve information about the authenticated user
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Current user information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized

  /auth/profile:
    get:
      summary: Get user profile
      description: Retrieve user profile including background information and personalization settings
      security:
        - BearerAuth: []
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: Unauthorized
    put:
      summary: Update user profile
      description: Update user profile including background information
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfile'
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: Unauthorized
        '400':
          description: Invalid request format

  /auth/personalize:
    post:
      summary: Get personalized content
      description: Retrieve content adapted to user's background and preferences
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                moduleId:
                  type: string
                  description: ID of the module/chapter to personalize
                content:
                  type: string
                  description: Original content to personalize
      responses:
        '200':
          description: Personalized content
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
                    description: Personalized content
                  metadata:
                    type: object
                    description: Information about personalization applied
        '401':
          description: Unauthorized

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: Unique user identifier
        email:
          type: string
          format: email
          description: User's email address
        name:
          type: string
          description: User's display name
        image:
          type: string
          format: uri
          description: Profile image URL
        emailVerified:
          type: string
          format: date-time
          description: When email was verified
        createdAt:
          type: string
          format: date-time
          description: Account creation timestamp
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp

    Session:
      type: object
      properties:
        id:
          type: string
          description: Session identifier
        userId:
          type: string
          description: Associated user ID
        expiresAt:
          type: string
          format: date-time
          description: Session expiration time
        createdAt:
          type: string
          format: date-time
          description: Session creation time

    BackgroundInfo:
      type: object
      properties:
        softwareSkills:
          type: object
          properties:
            python:
              type: string
              enum: [beginner, intermediate, advanced]
            ros:
              type: string
              enum: [beginner, intermediate, advanced]
            javascript:
              type: string
              enum: [beginner, intermediate, advanced]
            typescript:
              type: string
              enum: [beginner, intermediate, advanced]
        hardwareExperience:
          type: object
          properties:
            jetson:
              type: string
              enum: [none, beginner, intermediate, advanced]
            rtx:
              type: string
              enum: [none, beginner, intermediate, advanced]
            raspberryPi:
              type: string
              enum: [none, beginner, intermediate, advanced]
            arduino:
              type: string
              enum: [none, beginner, intermediate, advanced]
        roboticsExperience:
          type: string
          enum: [none, beginner, intermediate, advanced]

    UserProfile:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        backgroundInfo:
          $ref: '#/components/schemas/BackgroundInfo'
        personalizationSettings:
          type: object
          properties:
            difficultyPreference:
              type: string
              enum: [beginner, intermediate, advanced]
            contentFormatPreference:
              type: string
              enum: [text, visual, interactive]
            personalizationEnabled:
              type: boolean